name: Update Domain List

on:
  schedule:
    - cron: '*/20 * * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update_domein_list.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_domain_list:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm install
      - run: npm run generate:disposable_email_blocklist_json
      - run: npm run lint:fix
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update domain list
          delete-branch: true
          title: Update domain list
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: mziyut
          branch: create-pull-request/patch-pull-articles
